import fs from "node:fs";
import type { Pista } from "./briefing";
import { datosAip } from "./aip";
import path from "node:path";

/**
 * In-process aerodrome directory, loaded once from src/data/airports.tsv
 * (generated by scripts/build-airports.mjs from the OurAirports public-domain
 * dataset). ~17k rows / 755 KB, so keeping it in memory is far cheaper than a
 * round trip — resolving an ICAO while the pilot types has to feel instant.
 *
 * Server-only: this module touches the filesystem, never import it from a
 * client component.
 */

/** What ANAC publishes about an Argentine aerodrome in MADHEL. */
export interface MadhelInfo {
  /** Province, as MADHEL spells it (uppercase). */
  province: string;
  /** AD = aeródromo, HEL = helipuerto. */
  kind: "AD" | "HEL";
  /** PUBLICO / PRIVADO. Blank where MADHEL does not state it. */
  condition: string;
  /** null where MADHEL does not state it — not the same as "uncontrolled". */
  controlled: boolean | null;
  /** OK, CERRADO, SIN IDENTIFICACION VISUAL… verbatim, so a closed field says so. */
  status: string;
  /** Elevation in metres, the unit MADHEL and Argentine charts publish. */
  elevationM?: number;
}

export interface Airport {
  /** Canonical code: the ICAO indicator, or the ANAC designator when there is no
   *  ICAO. This is what gets written into a flight's route — see `local`. */
  icao: string;
  name: string;
  city: string;
  country: string;
  /** L = large, M = medium, S = small, H = heliport/seaplane. */
  size: "L" | "M" | "S" | "H";
  iata: string;
  /** Short label to show under an input, FlightDeck-style: SADM -> "Morón". */
  label: string;
  /** Field elevation in feet. Missing upstream for a handful of entries. */
  elevation?: number;
  /** Decimal degrees, 4dp (~11 m) — enough to plot, small enough not to bloat. */
  lat?: number;
  lon?: number;
  /**
   * Variación magnética en **grados oeste positivos**, precalculada con WMM por
   * `scripts/build-magvar.mjs` y guardada en la 14ª columna de `madhel.tsv`.
   *
   * Oeste positivo y no declinación este porque es la que se **suma** al rumbo
   * verdadero para obtener el magnético, que es lo único que el piloto hace con ella.
   *
   * Sólo la tienen los aeródromos de MADHEL. `undefined` es "no la sabemos" — y ojo
   * con confundirlo con cero: **cero es un valor válido en Argentina**, la línea
   * agónica cruza la Patagonia. El país va de 17,8° W en Misiones a 12,6° E en Santa
   * Cruz, así que una constante nacional estaría equivocada por treinta grados de
   * punta a punta.
   */
  variacionW?: number;
  /**
   * Pistas con **rumbo verdadero**, de `runways.tsv`. Vacío —no `undefined`— cuando el
   * aeródromo no tiene ninguna publicada, que es el caso de 618 de los 711 de MADHEL:
   * OurAirports sólo conoce los que tienen indicador ICAO.
   */
  pistas?: Pista[];
  /**
   * ANAC's three-letter designator — GEZ for General Rodríguez, MOR for Morón.
   * Argentine aerodromes only, and it is how pilots here actually refer to the
   * field. Resolves as an alias of `icao`; it is never what gets stored.
   */
  local?: string;
  madhel?: MadhelInfo;
}

interface Index {
  /** Keyed by canonical code **and** by ANAC designator, so "GEZ" and "SRDR"
   *  both land on the same object. */
  byIcao: Map<string, Airport>;
  /** ICAO prefix (2 chars) -> airports, so prefix search never scans all 17k. */
  byPrefix: Map<string, Airport[]>;
  all: Airport[];
  /** Pre-normalized "city name" per entry, parallel to `all`. Building this
   *  once at load turns the free-text pass into a plain substring scan. */
  haystacks: string[];
}

let index: Index | null = null;

/** Uppercase + strip diacritics, so "moron" matches "Morón". */
export function normalize(s: string): string {
  return s.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toUpperCase().trim();
}

/**
 * The upstream names are English and verbose ("Ezeiza International Airport -
 * Ministro Pistarini"). Pilots recognise the place, not the full legal name, so
 * prefer the municipality and fall back to a de-suffixed name.
 */
function shortLabel(name: string, city: string): string {
  if (city) return city;
  return name
    .replace(/\s+(International\s+)?(Airport|Airfield|Aerodrome|Air Base|Airstrip)$/i, "")
    .trim() || name;
}

function load(): Index {
  if (index) return index;

  const file = path.join(process.cwd(), "src", "data", "airports.tsv");
  const raw = fs.readFileSync(file, "utf8");

  const byIcao = new Map<string, Airport>();
  const byPrefix = new Map<string, Airport[]>();
  const all: Airport[] = [];
  const haystacks: string[] = [];

  for (const line of raw.split("\n")) {
    if (!line) continue;
    const [icao, name, city, country, size, iata, elev, lat, lon] = line.split("\t");
    const asNum = (v?: string) => {
      const n = parseFloat(v ?? "");
      return Number.isFinite(n) ? n : undefined;
    };
    if (!icao) continue;
    const airport: Airport = {
      icao,
      name,
      city: city || "",
      country: country || "",
      size: (size as Airport["size"]) || "S",
      iata: iata || "",
      label: shortLabel(name, city || ""),
      elevation: asNum(elev),
      lat: asNum(lat),
      lon: asNum(lon),
    };
    byIcao.set(icao, airport);
    all.push(airport);
    haystacks.push(normalize(`${airport.city} ${airport.name}`));
    const p = icao.slice(0, 2);
    const bucket = byPrefix.get(p);
    if (bucket) bucket.push(airport);
    else byPrefix.set(p, [airport]);
  }

  applyMadhel({ byIcao, byPrefix, all, haystacks });

  index = { byIcao, byPrefix, all, haystacks };
  return index;
}

/** Spanish title case: "GENERAL RODRÍGUEZ" -> "General Rodríguez". */
const MINOR_WORDS = new Set(["DE", "DEL", "LA", "LAS", "LO", "LOS", "Y", "EL", "EN"]);

function titleCase(s: string): string {
  return s
    .split(/\s+/)
    .map((word, i) =>
      i > 0 && MINOR_WORDS.has(word)
        ? word.toLowerCase()
        : word.charAt(0) + word.slice(1).toLowerCase()
    )
    .join(" ");
}

/**
 * Layers ANAC's MADHEL over the OurAirports base.
 *
 * OurAirports only knows the 164 Argentine aerodromes that hold an ICAO code.
 * MADHEL lists 711, and **558 of them have no ICAO at all** — General Rodríguez
 * is GEZ, and only GEZ, to everyone who flies there. Without this pass those
 * fields simply do not exist as far as the app is concerned.
 *
 * Two rules, and they are not symmetric:
 *
 * - For an aerodrome the base already has, MADHEL contributes **identity and
 *   category** (designator, province, público/privado, controlado, elevation)
 *   but leaves the name alone. The AR names in the base come from the
 *   hand-maintained overlay in `airports-overlay.tsv`, which is curated for
 *   exactly this purpose; overwriting "Aeródromo San Fernando" with MADHEL's
 *   "SAN FERNANDO" would throw away the better string.
 * - For one it does not have, MADHEL supplies everything.
 */
/**
 * Pistas por ICAO, leídas una vez.
 *
 * Archivo aparte y no una columna más de `madhel.tsv` porque la relación es de uno a
 * muchos: SAEZ tiene dos pistas y SACO también. Meterlas en una celda obligaría a
 * inventar un separador adentro de un TSV.
 */
function leerPistas(): Map<string, Pista[]> {
  const mapa = new Map<string, Pista[]>();
  const archivo = path.join(process.cwd(), "src", "data", "runways.tsv");
  if (!fs.existsSync(archivo)) return mapa;

  for (const linea of fs.readFileSync(archivo, "utf8").split("\n")) {
    if (!linea.trim()) continue;
    const [icao, le, he, rumbo, largo, superficie] = linea.split("\t");
    const rumboT = Number.parseFloat(rumbo);
    if (!icao || !Number.isFinite(rumboT)) continue;

    const largoFt = Number.parseFloat(largo);
    const lista = mapa.get(icao) ?? [];
    lista.push({
      le,
      he,
      rumboT,
      largoFt: Number.isFinite(largoFt) ? largoFt : undefined,
      superficie: superficie || undefined,
      // De OurAirports: rumbo verdadero publicado, no derivado del designador.
      fuente: "medida",
    });
    mapa.set(icao, lista);
  }
  return mapa;
}

/**
 * Corrige el largo de las pistas con el del AIP, donde el AIP lo publica.
 *
 * `runways.tsv` sale de OurAirports y **está bien en la enorme mayoría**: de las 52 pistas
 * comparables contra el AIP, 43 coinciden dentro de 15 m. Pero nueve no, y algunas por
 * mucho: **Morón figura con 2850 m y mide 2303** —547 m de más, confirmado contra las
 * distancias declaradas de AD 2.13, donde TORA, TODA, ASDA y LDA dicen todas 2.303— y San
 * Fernando figura con 1801 donde mide 1690.
 *
 * Un largo de más es del lado peligroso: es el número con el que alguien decide si su
 * avión entra. Así que donde ANAC publica la medida, gana ANAC.
 *
 * **El rumbo no se toca.** Sigue siendo el medido de OurAirports, que es el que alimenta el
 * viento cruzado y que se contrastó sin encontrar diferencias. El AIP lo da en magnético y
 * geográfico, y convertirlo sería agregar una conversión donde hoy hay una medición.
 */
function corregirLargosConAip(icao: string, pistas: Pista[]): Pista[] {
  const delAip = datosAip(icao)?.pistas;
  if (!delAip?.length) return pistas;

  const normalizar = (d: string) => d.split("/").map((x) => x.replace(/^0+/, "") || "0").join("/");

  return pistas.map((p) => {
    const par = delAip.find((a) => normalizar(a.designador) === normalizar(`${p.le}/${p.he}`));
    if (!par) return p;
    const metros = Number(par.dimensiones.split(/[xX×]/)[0].replace(".", ""));
    if (!Number.isFinite(metros) || metros <= 0) return p;
    return { ...p, largoFt: Math.round(metros * 3.28084) };
  });
}

function applyMadhel({ byIcao, byPrefix, all, haystacks }: Index): void {
  const pistasPorIcao = leerPistas();
  const file = path.join(process.cwd(), "src", "data", "madhel.tsv");
  if (!fs.existsSync(file)) return;

  for (const line of fs.readFileSync(file, "utf8").split("\n")) {
    if (!line) continue;
    const [local, icao, iata, name, city, province, kind, condition, control, status, elevM, lat, lon, magvarW] =
      line.split("\t");
    if (!local) continue;

    const asNum = (v?: string) => {
      const n = parseFloat(v ?? "");
      return Number.isFinite(n) ? n : undefined;
    };

    // The ICAO wins as the canonical code wherever one exists. That keeps every
    // flight already logged as SADM matching the aerodrome a pilot now reaches by
    // typing MOR: canonicalising the other way would split one aerodrome's
    // history in two the day this shipped.
    const canonical = icao || local;
    const metres = asNum(elevM);
    const madhel: MadhelInfo = {
      province: province || "",
      kind: kind === "HEL" ? "HEL" : "AD",
      condition: condition || "",
      controlled: control === "C" ? true : control === "NC" ? false : null,
      status: status || "",
      elevationM: metres,
    };

    const existing = byIcao.get(canonical);
    if (existing) {
      existing.local = local;
      existing.madhel = madhel;
      existing.variacionW = asNum(magvarW);
      existing.pistas = corregirLargosConAip(canonical, pistasPorIcao.get(canonical) ?? []);
      if (existing.elevation === undefined && metres !== undefined) {
        existing.elevation = Math.round(metres / 0.3048);
      }
      if (!existing.iata && iata) existing.iata = iata;
      byIcao.set(local, existing);
      continue;
    }

    const label = titleCase(name.split("/")[0].trim()) || city || local;
    const airport: Airport = {
      icao: canonical,
      // Kept verbatim as MADHEL publishes it — the official designation, which
      // the aerodrome page shows next to the friendlier `label`.
      name,
      city: city || "",
      country: "AR",
      size: kind === "HEL" ? "H" : "S",
      iata: iata || "",
      label,
      elevation: metres !== undefined ? Math.round(metres / 0.3048) : undefined,
      lat: asNum(lat),
      lon: asNum(lon),
      local,
      madhel,
      variacionW: asNum(magvarW),
      pistas: corregirLargosConAip(canonical, pistasPorIcao.get(canonical) ?? []),
    };

    byIcao.set(canonical, airport);
    if (local !== canonical) byIcao.set(local, airport);
    all.push(airport);
    // The designator goes in the haystack too, so a half-typed "GE" still
    // surfaces GEZ — the exact-match path only fires on the full code.
    haystacks.push(normalize(`${local} ${canonical} ${city} ${name} ${province}`));
    const p = canonical.slice(0, 2);
    const bucket = byPrefix.get(p);
    if (bucket) bucket.push(airport);
    else byPrefix.set(p, [airport]);
  }
}

/**
 * Exact code lookup. Accepts an ICAO indicator or an ANAC designator — `GEZ`
 * and `SRDR` both return General Rodríguez. Returns null for unknown codes.
 */
export function getAirport(icao: string): Airport | null {
  return load().byIcao.get(normalize(icao)) ?? null;
}

/**
 * Todos los aeródromos del directorio.
 *
 * Existe para `/api/airports/near`, que necesita recorrerlos para medir distancias. Es
 * el array vivo del índice y no una copia: **no lo mutes.** Devolver una copia de 711
 * objetos en cada request para protegerse de un `push` que nadie va a escribir sería
 * pagar por una precaución imaginaria.
 */
export function allAirports(): Airport[] {
  return load().all;
}

const SIZE_RANK: Record<Airport["size"], number> = { L: 0, M: 1, S: 2, H: 3 };

/**
 * Ranks by how the query matched (exact ICAO beats prefix beats free text),
 * then by aerodrome size, then Argentina first — Vector's pilots fly SA*, so a
 * two-letter query like "SA" should surface local fields, not Saudi ones.
 */
function compare(a: Airport, b: Airport, rankA: number, rankB: number): number {
  if (rankA !== rankB) return rankA - rankB;
  if (SIZE_RANK[a.size] !== SIZE_RANK[b.size]) return SIZE_RANK[a.size] - SIZE_RANK[b.size];
  const arA = a.country === "AR" ? 0 : 1;
  const arB = b.country === "AR" ? 0 : 1;
  if (arA !== arB) return arA - arB;
  return a.icao.localeCompare(b.icao);
}

/**
 * Prefix-first fuzzy search over ICAO, ANAC designator, IATA, city and name.
 * `limit` caps the response; callers typically want a handful of suggestions.
 *
 * The exact pass covers ANAC designators for free, because the index keys them
 * alongside ICAO codes. That ordering matters: **489 of the 711 MADHEL
 * designators are also somebody's IATA code** somewhere in the world, and an
 * Argentine logbook should answer "MOR" with Morón, not with a foreign field
 * that happens to share the letters. Exact beats IATA, so it does.
 */
export function searchAirports(query: string, limit = 8): Airport[] {
  return buscarEnIndice(load(), query, limit);
}

/**
 * Lo que necesita la búsqueda para funcionar, sin decir de dónde salió.
 *
 * Existe para que **el catálogo de a bordo use esta misma búsqueda** en vez de una
 * parecida. `catalogo-json.ts` arma este índice con los ~875 aeródromos argentinos
 * del JSON precacheado y llama acá; el servidor lo arma con los 17.129 del TSV.
 *
 * Sin esto, el orden de las sugerencias sin señal sería distinto del orden con señal
 * —el ranking de `compare` no es obvio de replicar— y el piloto vería otra lista
 * según tuviera o no red. Es la misma razón por la que la resolución de puntos se
 * sacó del route handler.
 */
export interface IndiceAerodromos {
  byIcao: Map<string, Airport>;
  byPrefix: Map<string, Airport[]>;
  all: Airport[];
  /** Texto normalizado y concatenado por aeródromo, en el mismo orden que `all`. */
  haystacks: string[];
}

/** Arma el índice desde una lista suelta. Lo usa el catálogo de a bordo. */
export function construirIndice(aerodromos: Airport[]): IndiceAerodromos {
  const byIcao = new Map<string, Airport>();
  const byPrefix = new Map<string, Airport[]>();
  const all: Airport[] = [];
  const haystacks: string[] = [];

  for (const a of aerodromos) {
    byIcao.set(normalize(a.icao), a);
    if (a.local && a.local !== a.icao) byIcao.set(normalize(a.local), a);
    all.push(a);
    haystacks.push(normalize(`${a.local ?? ""} ${a.icao} ${a.city} ${a.name}`));
    const p = normalize(a.icao).slice(0, 2);
    const bucket = byPrefix.get(p);
    if (bucket) bucket.push(a);
    else byPrefix.set(p, [a]);
  }

  return { byIcao, byPrefix, all, haystacks };
}

export function buscarEnIndice(indice: IndiceAerodromos, query: string, limit = 8): Airport[] {
  const q = normalize(query);
  if (q.length < 2) return [];

  const { byIcao, byPrefix, all, haystacks } = indice;
  const ranks = new Map<Airport, number>();

  const consider = (airport: Airport, rank: number) => {
    const current = ranks.get(airport);
    if (current === undefined || rank < current) ranks.set(airport, rank);
  };

  // 0 — exact ICAO. This is the common case: the pilot knows the code.
  const exact = byIcao.get(q);
  if (exact) consider(exact, 0);

  // 1 — ICAO prefix, restricted to the matching bucket.
  if (q.length >= 2 && /^[A-Z]{2,4}$/.test(q)) {
    for (const airport of byPrefix.get(q.slice(0, 2)) ?? []) {
      if (airport.icao.startsWith(q)) consider(airport, 1);
    }
  }

  // 2/3 — IATA, then city/name text. Only worth scanning when the prefix pass
  // came up short, since this is the only path that walks the whole table.
  if (ranks.size < limit) {
    for (let i = 0; i < all.length; i++) {
      if (q.length === 3 && all[i].iata === q) consider(all[i], 2);
      else if (haystacks[i].includes(q)) consider(all[i], 3);
    }
  }

  return [...ranks.entries()]
    .sort(([a, ra], [b, rb]) => compare(a, b, ra, rb))
    .slice(0, limit)
    .map(([airport]) => airport);
}
