import fs from "node:fs";
import path from "node:path";

/**
 * In-process aerodrome directory, loaded once from src/data/airports.tsv
 * (generated by scripts/build-airports.mjs from the OurAirports public-domain
 * dataset). ~17k rows / 755 KB, so keeping it in memory is far cheaper than a
 * round trip — resolving an ICAO while the pilot types has to feel instant.
 *
 * Server-only: this module touches the filesystem, never import it from a
 * client component.
 */

export interface Airport {
  icao: string;
  name: string;
  city: string;
  country: string;
  /** L = large, M = medium, S = small, H = heliport/seaplane. */
  size: "L" | "M" | "S" | "H";
  iata: string;
  /** Short label to show under an input, FlightDeck-style: SADM -> "Morón". */
  label: string;
}

interface Index {
  byIcao: Map<string, Airport>;
  /** ICAO prefix (2 chars) -> airports, so prefix search never scans all 17k. */
  byPrefix: Map<string, Airport[]>;
  all: Airport[];
  /** Pre-normalized "city name" per entry, parallel to `all`. Building this
   *  once at load turns the free-text pass into a plain substring scan. */
  haystacks: string[];
}

let index: Index | null = null;

/** Uppercase + strip diacritics, so "moron" matches "Morón". */
export function normalize(s: string): string {
  return s.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toUpperCase().trim();
}

/**
 * The upstream names are English and verbose ("Ezeiza International Airport -
 * Ministro Pistarini"). Pilots recognise the place, not the full legal name, so
 * prefer the municipality and fall back to a de-suffixed name.
 */
function shortLabel(name: string, city: string): string {
  if (city) return city;
  return name
    .replace(/\s+(International\s+)?(Airport|Airfield|Aerodrome|Air Base|Airstrip)$/i, "")
    .trim() || name;
}

function load(): Index {
  if (index) return index;

  const file = path.join(process.cwd(), "src", "data", "airports.tsv");
  const raw = fs.readFileSync(file, "utf8");

  const byIcao = new Map<string, Airport>();
  const byPrefix = new Map<string, Airport[]>();
  const all: Airport[] = [];
  const haystacks: string[] = [];

  for (const line of raw.split("\n")) {
    if (!line) continue;
    const [icao, name, city, country, size, iata] = line.split("\t");
    if (!icao) continue;
    const airport: Airport = {
      icao,
      name,
      city: city || "",
      country: country || "",
      size: (size as Airport["size"]) || "S",
      iata: iata || "",
      label: shortLabel(name, city || ""),
    };
    byIcao.set(icao, airport);
    all.push(airport);
    haystacks.push(normalize(`${airport.city} ${airport.name}`));
    const p = icao.slice(0, 2);
    const bucket = byPrefix.get(p);
    if (bucket) bucket.push(airport);
    else byPrefix.set(p, [airport]);
  }

  index = { byIcao, byPrefix, all, haystacks };
  return index;
}

/** Exact ICAO lookup. Returns null for unknown codes. */
export function getAirport(icao: string): Airport | null {
  return load().byIcao.get(normalize(icao)) ?? null;
}

const SIZE_RANK: Record<Airport["size"], number> = { L: 0, M: 1, S: 2, H: 3 };

/**
 * Ranks by how the query matched (exact ICAO beats prefix beats free text),
 * then by aerodrome size, then Argentina first — Vector's pilots fly SA*, so a
 * two-letter query like "SA" should surface local fields, not Saudi ones.
 */
function compare(a: Airport, b: Airport, rankA: number, rankB: number): number {
  if (rankA !== rankB) return rankA - rankB;
  if (SIZE_RANK[a.size] !== SIZE_RANK[b.size]) return SIZE_RANK[a.size] - SIZE_RANK[b.size];
  const arA = a.country === "AR" ? 0 : 1;
  const arB = b.country === "AR" ? 0 : 1;
  if (arA !== arB) return arA - arB;
  return a.icao.localeCompare(b.icao);
}

/**
 * Prefix-first fuzzy search over ICAO, IATA, city and name.
 * `limit` caps the response; callers typically want a handful of suggestions.
 */
export function searchAirports(query: string, limit = 8): Airport[] {
  const q = normalize(query);
  if (q.length < 2) return [];

  const { byIcao, byPrefix, all, haystacks } = load();
  const ranks = new Map<Airport, number>();

  const consider = (airport: Airport, rank: number) => {
    const current = ranks.get(airport);
    if (current === undefined || rank < current) ranks.set(airport, rank);
  };

  // 0 — exact ICAO. This is the common case: the pilot knows the code.
  const exact = byIcao.get(q);
  if (exact) consider(exact, 0);

  // 1 — ICAO prefix, restricted to the matching bucket.
  if (q.length >= 2 && /^[A-Z]{2,4}$/.test(q)) {
    for (const airport of byPrefix.get(q.slice(0, 2)) ?? []) {
      if (airport.icao.startsWith(q)) consider(airport, 1);
    }
  }

  // 2/3 — IATA, then city/name text. Only worth scanning when the prefix pass
  // came up short, since this is the only path that walks the whole table.
  if (ranks.size < limit) {
    for (let i = 0; i < all.length; i++) {
      if (q.length === 3 && all[i].iata === q) consider(all[i], 2);
      else if (haystacks[i].includes(q)) consider(all[i], 3);
    }
  }

  return [...ranks.entries()]
    .sort(([a, ra], [b, rb]) => compare(a, b, ra, rb))
    .slice(0, limit)
    .map(([airport]) => airport);
}
